export const PRODUC_REQUEST="PRODUC_REQUEST"
export const PRODUC_FAILURE="PRODUC_FAILURE"


export const GET_PRODUC_SUCCESS="GET_PRODUC_SUCCESS"
export const POST_PRODUC_SUCCESS="POST_PRODUC_SUCCESS"
