export const CART_PRODUC_REQUEST = "CART_PRODUC_REQUEST";
export const CART_PRODUC_FAILURE = "CART_PRODUC_FAILURE";
export const CART_GET_PRODUC_SUCCESS = "CART_GET_PRODUC_SUCCESS";
export const CART_POST_PRODUC_SUCCESS = "CART_POST_PRODUC_SUCCESS";
export const CART_DELETE_PRODUC_SUCCESS = "CART_DELETE_PRODUC_SUCCESS";
